# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install dependencies and set workdir
WORKDIR /app

# Copy project files
COPY pyproject.toml README.md .
COPY src/ ./src/

# Install pip and build tools
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install package
RUN pip install --no-cache-dir .

# Run server
CMD ["python", "src/server.py"]
